# Generated by Django 6.0.2 on 2026-02-11 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='Емкость (mAh)')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('end_warranty_date', models.DateField(verbose_name='Конец гарантийного срока')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('discount_percent', models.IntegerField(verbose_name='Скидка %')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveIntegerField(verbose_name='Оценка (1-5)')),
            ],
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('mileage', models.FloatField(default=0.0, verbose_name='Пробег (км)')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('rented', 'В аренде'), ('maintenance', 'На обслуживании')], default='available', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='ScooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('coordinates', models.CharField(max_length=100, verbose_name='Координаты')),
                ('max_capacity', models.IntegerField(verbose_name='Максимальная вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='TechService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, verbose_name='Тип обслуживания')),
                ('executor', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='TechSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('max_speed', models.IntegerField(verbose_name='Максимальная скорость (км/ч)')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время конца')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promo', verbose_name='Промокод')),
            ],
        ),
    ]
