# Generated by Django 6.0.2 on 2026-02-11 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.rental', verbose_name='Аренда'),
        ),
        migrations.AddField(
            model_name='review',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.rental'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rental',
            name='scooter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scooter', verbose_name='Самокат'),
        ),
        migrations.AddField(
            model_name='battery',
            name='scooter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='core.scooter', verbose_name='Самокат'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scootermodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station', verbose_name='Текущая станция'),
        ),
        migrations.AddField(
            model_name='rental',
            name='end_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_rentals', to='core.station'),
        ),
        migrations.AddField(
            model_name='rental',
            name='start_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_rentals', to='core.station'),
        ),
        migrations.AddField(
            model_name='techservice',
            name='scooter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scooter'),
        ),
        migrations.AddField(
            model_name='scootermodel',
            name='specs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.techspecs', verbose_name='Тех. характеристики'),
        ),
    ]
