# Generated by Django 6.0.2 on 2026-02-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='techspecs',
            name='country',
            field=models.CharField(default='Китай', max_length=100, verbose_name='Страна производства'),
        ),
    ]
