# Generated by Django 6.0.2 on 2026-02-13 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_techspecs_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='scooter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.scooter'),
        ),
    ]
