# Generated by Django 6.0.2 on 2026-02-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_review_scooter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='description',
        ),
        migrations.AddField(
            model_name='promo',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='promo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10, verbose_name='Скидка (%)'),
        ),
    ]
