# Generated by Django 6.0.2 on 2026-02-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('battery_level', models.IntegerField(default=100, verbose_name='Заряд %')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
        ),
    ]
