# Generated by Django 6.0.2 on 2026-02-06 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooter',
            name='battery_level',
        ),
        migrations.RemoveField(
            model_name='scooter',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='scooter',
            name='model_name',
        ),
        migrations.AddField(
            model_name='scooter',
            name='battery_charge',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scooter',
            name='current_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scooters', to='rentals.station'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('rented', 'В аренде'), ('charging', 'На зарядке')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='station',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Вместимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scooter',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
